In [12]:
import numpy as np

In [13]:
np_olympic_country=np.array(['GBR', 'Chine', 'RUS', 'US', 'KOR', 'JPN', 'GER'])

np_olympic_country_gold=np.array([29, 38, 24, 46, 13, 7, 11])

np_olympic_country_silver=np.array([17, 28, 25, 28, 8, 14, 11])

np_olympic_country_Bronze=np.array([19, 22, 32, 29, 7, 17, 14])

# 1 Find the country index with maximum gold?

In [14]:
max_gold_index = np.argmax(np_olympic_country_gold)

In [15]:
print("maximum gold index result is:",max_gold_index)

maximum gold index result is: 3


# 2. Print country with maximum Gold? 

In [20]:
country_with_max_gold = np_olympic_country[max_gold_index]

In [21]:
print("maximum gold index result is:,",country_with_max_gold)

maximum gold index result is:, US


# 3. Find countries with more than 20 gold medals
 

In [42]:
countries_with_more_than_20_gold = np_olympic_country[np_olympic_country_gold > 20]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 7

In [43]:
print("countries with more than 20 gold medals is: ",countries_with_more_than_20_gold)


NameError: name 'countries_with_more_than_20_gold' is not defined

# 4.Evaluate the dataset and print the medal:
    
    1.Print each country with no of gold medals

In [44]:
combined_data = np.column_stack((np_olympic_country, np_olympic_country_gold))

for country, gold_medals in combined_data:
    print(f"{country}: {gold_medals}")

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 5 and the array at index 1 has size 7

# 1. Create a 3X3X3X array with random values

In [47]:
import numpy as np

random = np.random.rand(3, 3, 3)

print(random)

[[[0.72416899 0.54242842 0.2490967 ]
  [0.31738591 0.84873862 0.56889028]
  [0.21432471 0.25496618 0.21679437]]

 [[0.0282612  0.9423201  0.90610678]
  [0.67785678 0.99299848 0.04759548]
  [0.51804359 0.38630228 0.23042597]]

 [[0.59315935 0.3143114  0.00787798]
  [0.88048793 0.5802387  0.4556411 ]
  [0.66274632 0.63982962 0.15326973]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [46]:
matrix = np.zeros((5, 5), dtype=int)

values = [1, 2, 3, 4]
np.fill_diagonal(matrix[1:], values)

print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern 

In [48]:
import numpy as np

matrix = np.zeros((8, 8), dtype=int)

matrix[::2, ::2] = 1
matrix[1::2, 1::2] = 1

print(matrix)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


# 4. Normalize a 5x5 random matrix 

In [49]:
import numpy as np

random = np.random.rand(5, 5)

Mean = np.mean(random)
Std = np.std(random)

normalized_matrix = (random - Mean) / Std

print("Original Matrix:")
print(random)

print("\nNormalized Matrix:")
print(normalized_matrix)

Original Matrix:
[[0.26217096 0.07939778 0.09473869 0.51473486 0.54964902]
 [0.24033448 0.33591596 0.78205221 0.62725086 0.46514152]
 [0.74673581 0.39983337 0.61505593 0.62537886 0.75820486]
 [0.75076436 0.29673656 0.55138962 0.86541187 0.10253772]
 [0.30421644 0.43953817 0.54085054 0.89426529 0.4153194 ]]

Normalized Matrix:
[[-0.97793627 -1.76142531 -1.69566385  0.10472281  0.25438844]
 [-1.07154214 -0.6618155   1.25062515  0.58704225 -0.10786766]
 [ 1.09923525 -0.3878224   0.53476654  0.57901757  1.14839935]
 [ 1.11650435 -0.82976483  0.26184982  1.60796086 -1.66223196]
 [-0.797701   -0.21762086  0.21667221  1.73164604 -0.32143886]]


# 5. How to find common values between two arrays?

In [50]:
array1 = np.array([7, 2, 1, 14, 5])
array2 = np.array([9, 4, 9, 6, 1])

common_values = np.intersect1d(array1, array2)
print(common_values)

[1]


#  6. How to get the dates of yesterday, today and tomorrow?

In [51]:
from datetime import datetime, timedelta

# Get the current date
today = datetime.now().date()

# Calculate the dates for yesterday and tomorrow
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

# Format the dates as strings
today_str = today.strftime("%Y-%m-%d")
yesterday_str = yesterday.strftime("%Y-%m-%d")
tomorrow_str = tomorrow.strftime("%Y-%m-%d")

print("Yesterday:", yesterday_str)
print("Today:", today_str)
print("Tomorrow:", tomorrow_str)

Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow: 2023-09-22


# 7. Consider two random array A and B, check if they are equal

In [14]:
import numpy as np

A = np.random.rand(5, 5),

B = np.random.rand (5, 5)

equal = np.array_equal(A, B)

if equal:
    print("Arrays A and B are equal.") 
else:
    print("Arrays A and B are not equal.")

Arrays A and B are not equal.


# 8.Create random vector of size 10 and replace the maximum value by 0

In [17]:
import numpy as np

random_vector= np.random.rand(10)

max_value = random_vector.max()

max_index = np.where(random_vector ==  max_value)[0]

random_vector[max_index] = 0

print("Random vector with the maximum value replaced:") 
print(random_vector)

Random vector with the maximum value replaced:
[0.71875823 0.72987053 0.79268324 0.34546844 0.67121631 0.
 0.09660611 0.44864679 0.8241958  0.42935403]


# 9. How to print all the values of an array?

In [3]:
import numpy as np

# Create a NumPy array
my_array = np.array([1, 2, 3, 4, 5])

# Print all the values of the array
print(my_array)

[1 2 3 4 5]


# 10.Subtract the mean of each row of a matrix

In [4]:
import numpy as np

# Create a sample matrix (you can replace this with your own matrix)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Calculate the mean of each row
row_means = np.mean(matrix, axis=1, keepdims=True)

# Subtract the row means from the matrix using broadcasting
normalized_matrix = matrix - row_means

print("Original Matrix:")
print(matrix)
print("\nMatrix with Row Means Subtracted:")
print(normalized_matrix)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix with Row Means Subtracted:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [5]:
import numpy as np

# Given vector
given_vector = np.array([10, 20, 30, 40, 50])

# Second vector with indices
indices_to_add_1 = np.array([1, 2, 3, 3, 4])

# Find unique indices and their counts
unique_indices, counts = np.unique(indices_to_add_1, return_counts=True)

# Add 1 to each element at the unique indices
given_vector[unique_indices] += counts

print("Given Vector:")
print(given_vector)

Given Vector:
[10 21 31 42 51]


# 12.How to get the diagonal of a dot product?

In [6]:
import numpy as np

# Create two matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Compute the dot product of the two matrices
dot_product = np.dot(matrix1, matrix2)

# Extract the diagonal elements using np.diag
diagonal_elements = np.diag(dot_product)

print("Dot Product:")
print(dot_product)

print("\nDiagonal Elements:")
print(diagonal_elements)

Dot Product:
[[19 22]
 [43 50]]

Diagonal Elements:
[19 50]


# 13.How to find the most frequent value in an array?

In [7]:
import numpy as np

array = np.array([1,2,4,3,5,4,3,1,4])
counts = np.bincount(array)
most_frequent_value = np.argmax(counts)

print("The most frequent value is:", most_frequent_value)

The most frequent value is: 4


# 14.How to get the n largest values of an array

In [8]:
import numpy as np

arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])

n = 3

partitioned_arr = np.partition(arr, -n)

n_largest_elements = partitioned_arr[-n:]

print("The", n, "largest elements are:", n_largest_elements)

The 3 largest elements are: [5 6 9]


# 15.How to create a record array from a regular array?

In [9]:
import numpy as np

regular_array = np.array([1,2,3,4,5])

record_array = np.rec.array(regular_array,dtype=[('my_column',int)])

print("Record Array:")   
print(record_array) 
print("Accessing 'my_coulmn':",record_array.my_column)

Record Array:
[(1,) (2,) (3,) (4,) (5,)]
Accessing 'my_coulmn': [1 2 3 4 5]


# 16. How to swap two rows of an array?

In [10]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

row1_index = 0  
row2_index = 2  

arr[row1_index], arr[row2_index] = arr[row2_index].copy(), arr[row1_index].copy()

print(arr)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


# 17. Write python code to reshape to the next dimension of numpy array?

In [11]:
import numpy as np

# Create a 1D array (replace this with your own array)
arr_1d = np.array([1, 2, 3, 4, 5, 6])

# Reshape it to the next dimension (2D)
arr_2d = arr_1d.reshape(-1, 1)

print("Original 1D Array:")
print(arr_1d)

print("\nReshaped 2D Array:")
print(arr_2d)

Original 1D Array:
[1 2 3 4 5 6]

Reshaped 2D Array:
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
